version: 2

sources:
  - name: API_datasus
    description: Fonte da API dos dados de vacinação da covid19
    schema: API_datasus
    tables:
      - name: datasus_vacinacao_COVID19
        description: Tabela geral com as informações sobre a aplicação de vacinas no Brasil.
        columns:
          - name: paciente_id
            description: Chave primaria da tabela datasus_vacinacao_COVID19
            tests: 
              - unique
              - not_null
          - name: paciente_idade
            description: Idade do paciente.
            tests:
              - not_null
          - name: paciente_enumSexoBiologico
            description: Sexo biológico do paciente.
            tests:
              - not_null
          - name: paciente_racaCor_codigo
            description: Código da raça/cor do paciente.
            tests:
              - not_null
          - name: paciente_racaCor_valor
            description: Descrição da raça/cor do paciente.
            tests:
              - not_null
          - name: paciente_endereco_nmMunicipio
            description: Nome do município de residência do paciente.
            tests:
              - not_null
          - name: paciente_endereco_uf
            description: Unidade federativa de residência do paciente.
            tests:
              - not_null
          - name: vacina_nome
            description: Nome da vacina aplicada.
            tests:
              - not_null
          - name: vacina_descricao_dose
            description: Descrição da dose da vacina aplicada.
            tests:
              - not_null
          - name: vacina_dataAplicacao
            description: Data de aplicação da vacina.
            tests:
              - not_null
